# Generated by Django 5.2.3 on 2025-07-14 16:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("item_requests", "0001_initial"),
        ("items", "0003_item_is_requested"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="request",
            options={
                "verbose_name": "Item_Request",
                "verbose_name_plural": "Item_Requests",
            },
        ),
        migrations.AlterUniqueTogether(
            name="request",
            unique_together={("item", "requester")},
        ),
    ]
