# Generated by Django 5.2.3 on 2025-07-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0002_alter_category_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="is_requested",
            field=models.BooleanField(default=False),
        ),
    ]
