# Generated by Django 5.2.1 on 2025-05-26 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("items", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("phone", models.CharField(max_length=50, verbose_name="Phone")),
                ("delivery_address", models.TextField(verbose_name="Delivery address")),
                (
                    "giver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="given_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Giver",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="items.item",
                        verbose_name="Item",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="made_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Requester",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
